Exception on / [GET]
Traceback (most recent call last):
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/appT/routes.py", line 7, in index
    return render_template('index.html', title='Home', user=user)
NameError: name 'user' is not defined
Exception on / [GET]
Traceback (most recent call last):
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/s0199669/github/PythonSampleCodes/Flask/projectT/appT/routes.py", line 7, in index
    user = 'Young'
NameError: name 'user' is not defined
